# WhatATheme
markdown: kramdown

# URL of the Site
url: http://zoeyzwee.github.io
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ""

# Title of the Site
title: Zoey Drassinower
subtitle: Data Science and Machine Learning
# Description of the Site
description: Zoey Drassinower's Data Science and Machine Learning Portfolio
# URL of Image of the Site
site-image: 
# Keywords of the Site
site-keywords: Zoey Drassinower, Drassinower, Zoey, Data Science, Machine Learning, Portfolio
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: zoey.drassinower@gmail.com
facebook_username:
twitter_username:
instagram_username: zweeeeeeeeeeeeee
linkedin_username: zoey-drassinower
github_username: ZoeyZwee
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics:

# Disqus
disqus-shortname:

# Name of the Author
author-name: Zoey Drassinower
# URL for the Image of the Author
author-image: https://github.com/ZoeyZwee/zoeyzwee.github.io/blob/3b47671e176f76502e3a05b4d08a925c481beb9b/assets/images/headshot.png?raw=true
# 60 Words About the Author
author-about: I'm Zoey Drassinower (they/she). I'm a data scientist and athlete, based in Toronto, Canada.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/ZoeyZwee

# Footer Bio Text
footer-bio: zoey.drassinower@gmail.com
# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
